### ISSUE TITLE
Server Not Starting

### ISSUE THREAD

**Issue by legomann97** [mortorqrobotics/MorScout#6]
Whenever I type node --harmony server while in the server folder, the command prompt says

events.js:85
   throw er; //Unhandled 'error' event

Error: listen EADDRINUSE
   at exports._errnoException (util.js:746:11)
   at Server._listen2 (net.js:1129:14)
   at listen (net.js:1155:10)
   at net.js:1253:9
   at dns.js:85:18
   at process._tickCallback (node.js:355:11)
   at Function.Module.runMain (module.js:503:11)
   at startup (node.js:129:16)
   at node.js:814:3

I have no clue what this is doing, so if you could help, that would be great!

**Comment by DaPasta** [comment]
Thanks for trying MorScout!
That error normally occurs when the port that the node.js server uses is already in use. By default, it uses port 8080. If you have any other program running on port 8080, you can either stop the other program, or change the port that the MorScout server uses. You can do this by typing the a different port after the "server" when you type in the command to start the server. 

For example: "node --harmony server 8082"

**Comment by legomann97** [comment]
Thank you so much! Do you have any idea how I could find out what is
running on 8080? Thanks!

**Comment by legomann97** [comment]
Actually nevermind! Port 8081 works fine.
